nome = str(input("Digite seu nome completo: ")).title().strip().split()
print("Muito prazer te conhecer!")
print(f"{nome}")
print(f"{(len(nome))}!")
print(f"Seu primeiro nome é {(nome[0])}!")
print(f"Seu ultimo nome é {nome[len(nome) - 1]}!")